In [105]:
import numpy as np
import pandas as pd

In [106]:
media = pd.read_csv(r"C:\Users\Ins 5584-1264\Downloads\movies.csv")

In [107]:
media.dtypes

show_id          object
type             object
title            object
director         object
country          object
date_added       object
release_year    float64
rating           object
duration         object
listed_in        object
dtype: object

In [108]:
media['duration'] = media['duration'].astype('|S')

In [109]:
media.dtypes

show_id          object
type             object
title            object
director         object
country          object
date_added       object
release_year    float64
rating           object
duration          |S146
listed_in        object
dtype: object

In [110]:
media.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020.0,PG-13,b'90 min',Documentaries
1,s2,TV Show,Blood & Water,NaN,South Africa,9/24/2021,2021.0,TV-MA,b'2 Seasons',"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,NaN,9/24/2021,2021.0,TV-MA,b'1 Season',"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,9/24/2021,2021.0,TV-MA,b'1 Season',"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,India,9/24/2021,2021.0,TV-MA,b'2 Seasons',"International TV Shows, Romantic TV Shows, TV ..."

In [111]:
media.shape

(8809, 10)

In [112]:
media.isnull()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False
3,False,False,False,True,True,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8804,False,False,False,False,False,False,False,False,False,False
8805,False,False,False,True,True,False,False,False,False,False
8806,False,False,False,False,False,False,False,False,False,False
8807,False,False,False,False,False,False,False,False,False,False
8808,False,False,False,False,False,False,False,False,False,False

In [113]:
media.isnull().sum().sort_values(ascending = False)
#here we can see that the director column has the most number of null values, followed by country. The other columns have only a few mull values

director        2636
country          833
date_added        13
rating             6
release_year       3
listed_in          3
title              2
type               1
show_id            0
duration           0
dtype: int64

In [114]:
media.head(2)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020.0,PG-13,b'90 min',Documentaries
1,s2,TV Show,Blood & Water,NaN,South Africa,9/24/2021,2021.0,TV-MA,b'2 Seasons',"International TV Shows, TV Dramas, TV Mysteries"

In [115]:
#to know what are the different ratings 
media['rating'].value_counts()

TV-MA                            3207
TV-14                            2160
TV-PG                             862
R                                 799
PG-13                             490
TV-Y7                             334
TV-Y                              307
PG                                287
TV-G                              220
NR                                 80
G                                  41
TV-Y7-FV                            6
UR                                  3
NC-17                               3
Classic Movies, Documentaries       1
74 min                              1
84 min                              1
66 min                              1
Name: rating, dtype: int64

In [116]:
media['type'].value_counts()
# there are more movies than TV shows listed. The duration is in seasons for the TV Shows and minutes for the movies
# this is useful for future analysis perhaps based on duration

Movie            6131
TV Show          2676
William Wyler       1
Name: type, dtype: int64

In [117]:
#showing all movies that were made by the United States
media[media['country'].isin(['United States'])]

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020.0,PG-13,b'90 min',Documentaries
9,s10,Movie,The Starling,Theodore Melfi,United States,9/24/2021,2021.0,PG-13,b'104 min',"Comedies, Dramas"
15,s16,TV Show,Dear White People,NaN,United States,9/22/2021,2021.0,TV-MA,b'4 Seasons',"TV Comedies, TV Dramas"
27,s28,Movie,Grown Ups,Dennis Dugan,United States,9/20/2021,2010.0,PG-13,b'103 min',Comedies
28,s29,Movie,Dark Skies,Scott Stewart,United States,9/19/2021,2013.0,PG-13,b'97 min',"Horror Movies, Sci-Fi & Fantasy"
...,...,...,...,...,...,...,...,...,...,...
8793,s8792,Movie,Young Adult,Jason Reitman,United States,11/20/2019,2011.0,R,b'94 min',"Comedies, Dramas, Independent Movies"
8795,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,United States,11/20/2019,2005.0,PG,b'88 min',"Children & Family Movies, Comedies"
8804,s8803,Movie,Zodiac,David Fincher,United States,11/20/2019,2007.0,R,b'158 min',"Cult Movies, Dramas, Thrillers"
8806,s8805,Movie,Zombieland,Ruben Fleischer,United States,11/1/2019,2009.0,R,b'88 min',"Comedies, Horror Movies"
8807,s8806,Movie,Zoom,Peter Hewitt,United States,1/11/2020,2006.0,PG,b'88 min',"Children & Family Movies, Comedies"

In [118]:
#to get a list of only movies 
movies = media[media['type'].isin(['Movie'])]

In [119]:
movies

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020.0,PG-13,b'90 min',Documentaries
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha",NaN,9/24/2021,2021.0,PG,b'91 min',Children & Family Movies
7,s8,Movie,Sankofa,Haile Gerima,"United States, Ghana, Burkina Faso, United Kin...",9/24/2021,1993.0,TV-MA,b'125 min',"Dramas, Independent Movies, International Movies"
9,s10,Movie,The Starling,Theodore Melfi,United States,9/24/2021,2021.0,PG-13,b'104 min',"Comedies, Dramas"
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Germany, Czech Republic",9/23/2021,2021.0,TV-MA,b'127 min',"Dramas, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8803,s8802,Movie,Zinzana,Majid Al Ansari,"United Arab Emirates, Jordan",3/9/2016,2015.0,TV-MA,b'96 min',"Dramas, International Movies, Thrillers"
8804,s8803,Movie,Zodiac,David Fincher,United States,11/20/2019,2007.0,R,b'158 min',"Cult Movies, Dramas, Thrillers"
8806,s8805,Movie,Zombieland,Ruben Fleischer,United States,11/1/2019,2009.0,R,b'88 min',"Comedies, Horror Movies"
8807,s8806,Movie,Zoom,Peter Hewitt,United States,1/11/2020,2006.0,PG,b'88 min',"Children & Family Movies, Comedies"
8808,s8807,Movie,Zubaan,Mozez Singh,India,3/2/2019,2015.0,TV-14,b'111 min',"Dramas, International Movies, Music & Musicals"

In [120]:
movies.dtypes

show_id          object
type             object
title            object
director         object
country          object
date_added       object
release_year    float64
rating           object
duration          |S146
listed_in        object
dtype: object

In [121]:
movies.isnull().sum().sort_values(ascending = False)

country         441
director        189
rating            3
date_added        1
release_year      1
listed_in         1
show_id           0
type              0
title             0
duration          0
dtype: int64

In [122]:
movies['rating'].value_counts()

TV-MA       2062
TV-14       1427
R            797
TV-PG        539
PG-13        490
PG           287
TV-Y7        139
TV-Y         131
TV-G         126
NR            75
G             41
TV-Y7-FV       5
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: rating, dtype: int64

In [123]:
#I'd like to filter down to movies that can be watched with the family 
movies[movies['rating'].isin(['G', 'PG-13', 'PG'])]
#I see that I have 818 options

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020.0,PG-13,b'90 min',Documentaries
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha",NaN,9/24/2021,2021.0,PG,b'91 min',Children & Family Movies
9,s10,Movie,The Starling,Theodore Melfi,United States,9/24/2021,2021.0,PG-13,b'104 min',"Comedies, Dramas"
27,s28,Movie,Grown Ups,Dennis Dugan,United States,9/20/2021,2010.0,PG-13,b'103 min',Comedies
28,s29,Movie,Dark Skies,Scott Stewart,United States,9/19/2021,2013.0,PG-13,b'97 min',"Horror Movies, Sci-Fi & Fantasy"
...,...,...,...,...,...,...,...,...,...,...
8769,s8768,Movie,XXX: State of the Union,Lee Tamahori,United States,1/1/2019,2005.0,PG-13,b'101 min',Action & Adventure
8778,s8777,Movie,Yellowbird,Christian De Vita,"France, Belgium",8/5/2015,2014.0,PG,b'90 min',"Children & Family Movies, Comedies"
8784,s8783,Movie,Yoga Hosers,Kevin Smith,United States,12/2/2016,2016.0,PG-13,b'88 min',"Comedies, Horror Movies, Independent Movies"
8795,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,United States,11/20/2019,2005.0,PG,b'88 min',"Children & Family Movies, Comedies"
8807,s8806,Movie,Zoom,Peter Hewitt,United States,1/11/2020,2006.0,PG,b'88 min',"Children & Family Movies, Comedies"

In [124]:
movies['duration'] = movies['duration'].astype('string')
#I'd like the duration to be less than 100 minutes

<ipython-input-124-df5f71ad9396>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['duration'] = movies['duration'].astype('string')

In [125]:
movies.dtypes

show_id          object
type             object
title            object
director         object
country          object
date_added       object
release_year    float64
rating           object
duration         string
listed_in        object
dtype: object

In [126]:
movies['duration'] = movies['duration'].str.upper()

<ipython-input-126-5835382d8f96>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['duration'] = movies['duration'].str.upper()

In [127]:
movies['duration'] = movies['duration'].str.replace(' MIN', '')

<ipython-input-127-9aa28668bd6b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['duration'] = movies['duration'].str.replace(' MIN', '')

In [144]:
movies['duration']

0        90
6        91
7       125
9       104
12      127
       ...
8803     96
8804    158
8806     88
8807     88
8808    111
Name: duration, Length: 6131, dtype: string

In [145]:
movies['duration']

0        90
6        91
7       125
9       104
12      127
       ...
8803     96
8804    158
8806     88
8807     88
8808    111
Name: duration, Length: 6131, dtype: string

In [162]:
#movies['duration'].fillna(movies['duration'].mean(), inplace = True)
#movies['duration'].fillna(0)
#movies['duration'] = movies['duration'].astype(int)
pd.set_option('display.max_rows', 300)
movies['duration'].head(300)
#not able to move forward

0       90
6       91
7      125
9      104
12     127
13      91
16      67
18      94
22     161
23      61
24     166
26     147
27     103
28      97
29     106
30     111
35     110
36     105
38      96
41     124
42     116
43      98
44      91
45      23
46     115
48     122
51      99
52      99
53      88
54     100
56     102
57      93
58      96
59      95
60      85
61      97
62      95
63      83
64     103
68     113
71      13
73     182
75     106
77      48
78     145
79     145
80      93
81     106
84     147
86      87
88      96
90      95
91      92
93      91
94      90
96      97
101     80
103    117
105    128
107     90
112    119
113    110
114    143
115    119
116    114
117     94
118    106
119     99
122    118
126    115
127     95
128    115
129    108
130     63
131    117
133    121
134    142
135    113
136    154
137     95
138    108
139    120
140    100
141     82
142    124
143    114
144    104
145     94
146     94
149     93
150     97
151    109
152     88
155    101
156    105
157    102
158    101
159    103
161    106
162    118
163     86
164    121
166    229
167     76
168     95
169     98
170     89
171    120
172    110
173     83
174    121
175    105
176     94
177    156
178    112
179     95
180    107
182    114
183    129
185     86
188     97
190    125
191    107
192    127
195    128
196     92
199    135
200    124
201    136
202    165
203    124
204    136
205    150
206    112
207    119
208    133
209    142
210     93
211    113
214    124
215    116
216    106
217    145
221     93
227     95
228    108
229     90
230     86
231     92
233     82
235     70
236    122
237    122
238    122
239    122
240     84
244     96
246    115
247    110
249     88
250    102
251     91
252    105
253    135
255     86
256    140
257    133
258     92
259     82
261     97
262     78
264     94
267    121
268     97
270    110
278     64
279     59
281    101
282    127
283     90
284    114
285    108
290     70
292     98
293     86
294    139
295    111
298    115
299    102
300    100
301    135
302     69
303     95
304     97
305    124
306    118
307    115
308    115
314    104
315    106
317    102
318     97
325     87
326     88
327    114
328     90
329    142
330     90
332    105
333    103
334    116
335    113
337     99
339     96
340    148
341    189
342     97
343    102
344     99
345     85
346    112
347     91
348     91
349    141
350    130
351     98
352    105
353    101
354    105
355    118
356     97
357    102
358    114
359    111
360    125
362     76
363    118
365    103
367    114
371     95
372    138
373    112
374     94
375    102
377     92
378     81
383    143
384     86
387    132
389    117
392    165
393     91
394     97
395     97
396    123
398     94
402    111
404     85
405     65
406     64
407     68
408     67
409     66
410     64
411     64
412     65
413     64
414     68
415     68
416     64
417     62
418     63
419     69
420     70
421     63
422     68
423     74
424     68
426     99
427     90
428     87
429    105
432    106
433    102
436     91
437     88
438    107
439    101
441    114
443    123
445     94
446    105
447    117
448    115
449    124
450    131
451    122
452    113
454     91
455    100
Name: duration, dtype: string

In [ ]:
#could add some more minutes to duration to factor in ad time/popcorn break for kids - but can't because string column right now